<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5qy7efu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5qy7efu/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5qy7efu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5qy7efu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5qy7efu\appProdProjectContainer([
    'container.build_hash' => '5qy7efu',
    'container.build_id' => 'e47fae83',
    'container.build_time' => 1560845794,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5qy7efu');
